# # "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: personalpeterpark
# # "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# app: text-recognition-service
# # "service" is the name of this project. This will also be added to your AWS resource names.
# service: text-recognition-service

service: text-recognition-service

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    - Effect: Allow
      Action:
        - textract:DetectDocumentText
      Resource: '*'

functions:
  proxy:
    handler: proxy.handler
    events:
      - http:
          path: recognize
          method: post

  textRecognition:
    handler: text_recognition.handler
    memorySize: 1024
    timeout: 30

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
