service: text-recognition-service

layers:
  tesseractAl2:
    path: amazonlinux-2
    compatibleRuntimes:
      - python3.8

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - textract:DetectDocumentText
      Resource: "*"
  ecr:
    images:
      tesseract:
        path: .  # points to Dockerfile
  architecture: x86_64

functions:
  proxy:
    handler: proxy.handler
    events:
      - http:
          path: recognize
          method: post

  textRecognition:
    image:
      name: tesseract


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
